import * as HELPERS from "@/scripts/helpers";

async function readRefProgramAsObject() {
  const program = structuredClone(PROGRAM);
  const programObj = {};
  program.forEach((p, i) => (programObj[`${i}`] = p));
  return programObj;
}

function cleanProgram(_programObj) {
  const programObj = JSON.parse(JSON.stringify(_programObj));

  for (let key in _programObj) {
    programObj[key].quantity = Number(programObj[key].quantity);
    programObj[key].area_min = Number(programObj[key].area_min);
    programObj[key].area_max = Number(programObj[key].area_max);
    programObj[key].x_min = Number(programObj[key].x_min);
    programObj[key].x_max = Number(programObj[key].x_max);
    programObj[key].y_min = Number(programObj[key].y_min);
    programObj[key].y_max = Number(programObj[key].y_max);
    programObj[key].zone_adj = HELPERS.toArray(programObj[key].zone_adj);
    programObj[key].space_adj = HELPERS.toArray(programObj[key].space_adj);
  }

  return programObj;
}

export async function initUserProgram(_program) {}

export async function initBaseProgram() {
  const program = await readRefProgramAsObject();
  return cleanProgram(program);
}

const PROGRAM = [
  {
    space_id: 0,
    space_name: "walk-in_entrance",
    quantity: 1,
    area_min: 9,
    area_max: 16,
    x_min: 3,
    x_max: 4,
    y_min: 3,
    y_max: 4,
    space_adj: "1,2,9",
    zone_name: "entrance",
    zone_adj: 2,
    zone_id: 0,
    program_type: "Ent",
    placement_priority: 10,
    changing_priority: 10,
  },
  {
    space_id: 1,
    space_name: "police",
    quantity: 1,
    area_min: 4,
    area_max: 5.76,
    x_min: 2,
    x_max: 2.4,
    y_min: 2,
    y_max: 2.4,
    space_adj: 0,
    zone_name: "entrance",
    zone_adj: "",
    zone_id: 1,
    program_type: "Pub",
    placement_priority: 5,
    changing_priority: 10,
  },
  {
    space_id: 2,
    space_name: "equipment1",
    quantity: 1,
    area_min: 1.44,
    area_max: 9,
    x_min: 1.2,
    x_max: 3,
    y_min: 1.2,
    y_max: 3,
    space_adj: 0,
    zone_name: "entrance",
    zone_adj: "",
    zone_id: 1,
    program_type: "Pub",
    placement_priority: 7,
    changing_priority: 10,
  },
  {
    space_id: 3,
    space_name: "reception",
    quantity: 1,
    area_min: 1.44,
    area_max: 4,
    x_min: 1.2,
    x_max: 2,
    y_min: 1.2,
    y_max: 2,
    space_adj: "4,5,9",
    zone_name: "reception",
    zone_adj: "1,3",
    zone_id: 2,
    program_type: "Pub",
    placement_priority: 7,
    changing_priority: 10,
  },
  {
    space_id: 4,
    space_name: "cash",
    quantity: 1,
    area_min: 1.44,
    area_max: 4,
    x_min: 1.2,
    x_max: 2,
    y_min: 1.2,
    y_max: 2,
    space_adj: "3,5,9",
    zone_name: "reception",
    zone_adj: "",
    zone_id: 2,
    program_type: "Pub",
    placement_priority: 7,
    changing_priority: 10,
  },
  {
    space_id: 5,
    space_name: "release",
    quantity: 1,
    area_min: 1.44,
    area_max: 4,
    x_min: 1.2,
    x_max: 2,
    y_min: 1.2,
    y_max: 2,
    space_adj: "3,4,9",
    zone_name: "reception",
    zone_adj: "",
    zone_id: 2,
    program_type: "Pub",
    placement_priority: 7,
    changing_priority: 10,
  },
  {
    space_id: 6,
    space_name: "wc",
    quantity: 1,
    area_min: 5.76,
    area_max: 12.96,
    x_min: 2.4,
    x_max: 3.6,
    y_min: 2.4,
    y_max: 3.6,
    space_adj: 9,
    zone_name: "common",
    zone_adj: "2,4,5,7",
    zone_id: 3,
    program_type: "Pub",
    placement_priority: 5,
    changing_priority: 10,
  },
  {
    space_id: 7,
    space_name: "triage",
    quantity: 1,
    area_min: 5.76,
    area_max: 23.04,
    x_min: 2.4,
    x_max: 4.8,
    y_min: 2.4,
    y_max: 4.8,
    space_adj: "9,14",
    zone_name: "common",
    zone_adj: "",
    zone_id: 3,
    program_type: "Reg",
    placement_priority: 10,
    changing_priority: 5,
  },
  {
    space_id: 8,
    space_name: "main_corridor1",
    quantity: 1,
    area_min: 9,
    area_max: 144,
    x_min: 3,
    x_max: 12,
    y_min: 3,
    y_max: 12,
    space_adj: "9,10,11,12",
    zone_name: "corridor",
    zone_adj: "3,4",
    zone_id: 100,
    program_type: "Cor",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 9,
    space_name: "waiting",
    quantity: 1,
    area_min: 12.96,
    area_max: 23.04,
    x_min: 3.6,
    x_max: 4.8,
    y_min: 3.6,
    y_max: 4.8,
    space_adj: "0,1,2,3,4,5,6,7,8,14,29",
    zone_name: "outpatient",
    zone_adj: 3,
    zone_id: 4,
    program_type: "Pub",
    placement_priority: 6,
    changing_priority: 10,
  },
  {
    space_id: 10,
    space_name: "treatment",
    quantity: 2,
    area_min: 11.52,
    area_max: 11.52,
    x_min: 3.1,
    x_max: 4.8,
    y_min: 3.1,
    y_max: 4.8,
    space_adj: 8,
    zone_name: "outpatient",
    zone_adj: "",
    zone_id: 5,
    program_type: "KPU",
    placement_priority: 10,
    changing_priority: 5,
  },
  {
    space_id: 11,
    space_name: "injection",
    quantity: 3,
    area_min: 11.52,
    area_max: 11.52,
    x_min: 2.4,
    x_max: 4.8,
    y_min: 2.4,
    y_max: 4.8,
    space_adj: 8,
    zone_name: "outpatient",
    zone_adj: "",
    zone_id: 5,
    program_type: "KPU",
    placement_priority: 10,
    changing_priority: 5,
  },
  {
    space_id: 12,
    space_name: "ECG",
    quantity: 1,
    area_min: 11.52,
    area_max: 11.52,
    x_min: 2.4,
    x_max: 2.4,
    y_min: 4.8,
    y_max: 4.8,
    space_adj: 8,
    zone_name: "outpatient",
    zone_adj: "",
    zone_id: 5,
    program_type: "KPU",
    placement_priority: 9,
    changing_priority: 5,
  },
  {
    space_id: 13,
    space_name: "main_corridor2",
    quantity: 1,
    area_min: 8.64,
    area_max: 41.4,
    x_min: 3.6,
    x_max: 11.5,
    y_min: 2.4,
    y_max: 3.6,
    space_adj: "14,15,16,18,19,20,21",
    zone_name: "corridor",
    zone_adj: "3,5",
    zone_id: 100,
    program_type: "Cor",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 14,
    space_name: "ambulance_entrance",
    quantity: 1,
    area_min: 5.76,
    area_max: 23.04,
    x_min: 2.4,
    x_max: 4.8,
    y_min: 2.4,
    y_max: 4.8,
    space_adj: "7,9,13,29",
    zone_name: "emergency_ent",
    zone_adj: "3,6,7",
    zone_id: 14,
    program_type: "Ent",
    placement_priority: 10,
    changing_priority: 10,
  },
  {
    space_id: 15,
    space_name: "CPR",
    quantity: 1,
    area_min: 23.04,
    area_max: 36,
    x_min: 4.8,
    x_max: 6,
    y_min: 4.8,
    y_max: 6,
    space_adj: "13,16",
    zone_name: "operation",
    zone_adj: "",
    zone_id: 7,
    program_type: "Reg",
    placement_priority: 10,
    changing_priority: 0,
  },
  {
    space_id: 16,
    space_name: "operation_room",
    quantity: 1,
    area_min: 36,
    area_max: 36,
    x_min: 6,
    x_max: 6,
    y_min: 6,
    y_max: 6,
    space_adj: "13,15,17,18",
    zone_name: "operation",
    zone_adj: "",
    zone_id: 7,
    program_type: "Reg",
    placement_priority: 10,
    changing_priority: 0,
  },
  {
    space_id: 17,
    space_name: "steril",
    quantity: 1,
    area_min: 1.44,
    area_max: 4,
    x_min: 1.2,
    x_max: 2,
    y_min: 1.2,
    y_max: 2,
    space_adj: 16,
    zone_name: "operation",
    zone_adj: "",
    zone_id: 7,
    program_type: "Reg",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 18,
    space_name: "scrub",
    quantity: 1,
    area_min: 1.44,
    area_max: 4,
    x_min: 1.2,
    x_max: 2,
    y_min: 1.2,
    y_max: 2,
    space_adj: "13,16",
    zone_name: "operation",
    zone_adj: "",
    zone_id: 7,
    program_type: "Reg",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 19,
    space_name: "casting",
    quantity: 1,
    area_min: 16,
    area_max: 36,
    x_min: 3.1,
    x_max: 3.1,
    y_min: 6,
    y_max: 6,
    space_adj: 13,
    zone_name: "emergency",
    zone_adj: "",
    zone_id: 6,
    program_type: "Reg",
    placement_priority: 8,
    changing_priority: 8,
  },
  {
    space_id: 20,
    space_name: "supervisor",
    quantity: 1,
    area_min: 5.76,
    area_max: 23.04,
    x_min: 2.9,
    x_max: 2.9,
    y_min: 6,
    y_max: 6,
    space_adj: 13,
    zone_name: "emergency",
    zone_adj: "",
    zone_id: 6,
    program_type: "Reg",
    placement_priority: 7,
    changing_priority: 8,
  },
  {
    space_id: 21,
    space_name: "main_corridor3",
    quantity: 1,
    area_min: 8.64,
    area_max: 41.4,
    x_min: 3.6,
    x_max: 11.5,
    y_min: 2.4,
    y_max: 3.6,
    space_adj: "13,22,23,24,25,27,28",
    zone_name: "corridor",
    zone_adj: "5,6",
    zone_id: 100,
    program_type: "Cor",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 22,
    space_name: "men_curing_cabin",
    quantity: 6,
    area_min: 7.02,
    area_max: 7.02,
    x_min: 2,
    x_max: 2,
    y_min: 3,
    y_max: 3,
    space_adj: 21,
    zone_name: "curing",
    zone_adj: "5,7",
    zone_id: 10,
    program_type: "KPU",
    placement_priority: 10,
    changing_priority: 1,
  },
  {
    space_id: 23,
    space_name: "women_curing_cabin",
    quantity: 6,
    area_min: 7.02,
    area_max: 7.02,
    x_min: 2,
    x_max: 2,
    y_min: 3,
    y_max: 3,
    space_adj: 21,
    zone_name: "curing",
    zone_adj: "",
    zone_id: 11,
    program_type: "KPU",
    placement_priority: 10,
    changing_priority: 1,
  },
  {
    space_id: 24,
    space_name: "isolated_room",
    quantity: 2,
    area_min: 21.6,
    area_max: 21.6,
    x_min: 3.6,
    x_max: 3.6,
    y_min: 6,
    y_max: 6,
    space_adj: 21,
    zone_name: "curing",
    zone_adj: "",
    zone_id: 9,
    program_type: "KPU",
    placement_priority: 10,
    changing_priority: 0,
  },
  {
    space_id: 25,
    space_name: "nurse_station",
    quantity: 1,
    area_min: 5.76,
    area_max: 16,
    x_min: 2.4,
    x_max: 4,
    y_min: 2.4,
    y_max: 4,
    space_adj: "21,26",
    zone_name: "curing",
    zone_adj: "",
    zone_id: 8,
    program_type: "Reg",
    placement_priority: 10,
    changing_priority: 8,
  },
  {
    space_id: 26,
    space_name: "clean_utility",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 25,
    zone_name: "curing",
    zone_adj: "",
    zone_id: 8,
    program_type: "Reg",
    placement_priority: 9,
    changing_priority: 10,
  },
  {
    space_id: 27,
    space_name: "equipment2",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 28,
    zone_name: "curing",
    zone_adj: "",
    zone_id: 8,
    program_type: "Reg",
    placement_priority: 5,
    changing_priority: 10,
  },
  {
    space_id: 28,
    space_name: "wc",
    quantity: 1,
    area_min: 5.76,
    area_max: 12.96,
    x_min: 2.4,
    x_max: 3.6,
    y_min: 2.4,
    y_max: 3.6,
    space_adj: 21,
    zone_name: "curing",
    zone_adj: "",
    zone_id: 8,
    program_type: "Pub",
    placement_priority: 5,
    changing_priority: 10,
  },
  {
    space_id: 29,
    space_name: "main_corridor4",
    quantity: 1,
    area_min: 8.64,
    area_max: 41.4,
    x_min: 3.6,
    x_max: 11.5,
    y_min: 2.4,
    y_max: 3.6,
    space_adj: "9,14,30,31,32,33,34,36,40",
    zone_name: "corridor",
    zone_adj: "3,5,6,7",
    zone_id: 100,
    program_type: "Cor",
    placement_priority: 9,
    changing_priority: 9,
  },
  {
    space_id: 30,
    space_name: "closet_room",
    quantity: 2,
    area_min: 12.96,
    area_max: 25,
    x_min: 3.6,
    x_max: 5,
    y_min: 3.6,
    y_max: 5,
    space_adj: 29,
    zone_name: "service",
    zone_adj: "3,5,6",
    zone_id: 12,
    program_type: "Reg",
    placement_priority: 8,
    changing_priority: 9,
  },
  {
    space_id: 31,
    space_name: "rest_room",
    quantity: 2,
    area_min: 5.76,
    area_max: 23.04,
    x_min: 3,
    x_max: 4.8,
    y_min: 3,
    y_max: 4.8,
    space_adj: 29,
    zone_name: "service",
    zone_adj: "",
    zone_id: 12,
    program_type: "Reg",
    placement_priority: 8,
    changing_priority: 9,
  },
  {
    space_id: 32,
    space_name: "kitchenette",
    quantity: 1,
    area_min: 5.76,
    area_max: 5.76,
    x_min: 2.4,
    x_max: 2.4,
    y_min: 2.4,
    y_max: 2.4,
    space_adj: 29,
    zone_name: "service",
    zone_adj: "",
    zone_id: 12,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 33,
    space_name: "service_pre_entrance",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: "29,35,37,38,39",
    zone_name: "service",
    zone_adj: "",
    zone_id: 12,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 34,
    space_name: "cleaning_room",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 34,
    zone_name: "service",
    zone_adj: "",
    zone_id: 13,
    program_type: "Reg",
    placement_priority: 6,
    changing_priority: 10,
  },
  {
    space_id: 35,
    space_name: "equipment_depot",
    quantity: 1,
    area_min: 5.76,
    area_max: 5.76,
    x_min: 2.4,
    x_max: 2.4,
    y_min: 2.4,
    y_max: 2.4,
    space_adj: 29,
    zone_name: "service",
    zone_adj: "",
    zone_id: 13,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 36,
    space_name: "cleaned_cloths_room",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 34,
    zone_name: "service",
    zone_adj: "",
    zone_id: 13,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 37,
    space_name: "soiled_cloths_goods_room",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 34,
    zone_name: "service",
    zone_adj: "",
    zone_id: 13,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 38,
    space_name: "soiled_utility",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 34,
    zone_name: "service",
    zone_adj: "",
    zone_id: 13,
    program_type: "Reg",
    placement_priority: 4,
    changing_priority: 10,
  },
  {
    space_id: 39,
    space_name: "electricity_room",
    quantity: 1,
    area_min: 1.44,
    area_max: 5.76,
    x_min: 1.2,
    x_max: 2.4,
    y_min: 1.2,
    y_max: 2.4,
    space_adj: 29,
    zone_name: "service",
    zone_adj: "",
    zone_id: 15,
    program_type: "Reg",
    placement_priority: 3,
    changing_priority: 10,
  },
];
